-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 13:20:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `id_cargo` INT NOT NULL,
  `nome_cargo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome_equipe` VARCHAR(45) NOT NULL,
  `numero_recursos_equipe` INT NOT NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enderecos` (
  `id_endereco` INT NOT NULL,
  `rua_endereco` VARCHAR(150) NOT NULL,
  `numero_endereco` INT NOT NULL,
  `bairro_endereco` VARCHAR(100) NOT NULL,
  `cidade_endereco` VARCHAR(100) NOT NULL,
  `estado_endereco` VARCHAR(45) NOT NULL,
  `CEP_endereco` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recursos` (
  `id_recurso` INT NOT NULL AUTO_INCREMENT,
  `nome_recurso` VARCHAR(100) NOT NULL,
  `salario_recurso` DECIMAL NOT NULL,
  `Cargo_id_cargo` INT NOT NULL,
  `Equipe_id_equipe` INT NOT NULL,
  `Enderecos_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_recurso`),
  INDEX `fk_Recursos_Cargo_idx` (`Cargo_id_cargo` ASC) VISIBLE,
  INDEX `fk_Recursos_Equipe1_idx` (`Equipe_id_equipe` ASC) VISIBLE,
  INDEX `fk_Recursos_Enderecos1_idx` (`Enderecos_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Recursos_Cargo`
    FOREIGN KEY (`Cargo_id_cargo`)
    REFERENCES `mydb`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_Equipe1`
    FOREIGN KEY (`Equipe_id_equipe`)
    REFERENCES `mydb`.`Equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_Enderecos1`
    FOREIGN KEY (`Enderecos_id_endereco`)
    REFERENCES `mydb`.`Enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `tipo_telefone` VARCHAR(45) NOT NULL,
  `numero_telefone` CHAR(11) NOT NULL,
  `Recursos_id_recurso` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_Telefone_Recursos1_idx` (`Recursos_id_recurso` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Recursos1`
    FOREIGN KEY (`Recursos_id_recurso`)
    REFERENCES `mydb`.`Recursos` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ferramenta` (
  `id_ferramenta` INT NOT NULL AUTO_INCREMENT,
  `nome_ferramenta` VARCHAR(100) NOT NULL,
  `versao_ferramenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ferramenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ferramenta` (
  `id_ferramenta` INT NOT NULL AUTO_INCREMENT,
  `nome_ferramenta` VARCHAR(100) NOT NULL,
  `versao_ferramenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ferramenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recursos_Ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recursos_Ferramenta` (
  `Recursos_id_recurso` INT NOT NULL,
  `Ferramenta_id_ferramenta` INT NOT NULL,
  `id_Recursos_Ferramenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Recursos_id_recurso`, `Ferramenta_id_ferramenta`, `id_Recursos_Ferramenta`),
  INDEX `fk_Recursos_has_Ferramenta_Ferramenta1_idx` (`Ferramenta_id_ferramenta` ASC) VISIBLE,
  INDEX `fk_Recursos_has_Ferramenta_Recursos1_idx` (`Recursos_id_recurso` ASC) VISIBLE,
  CONSTRAINT `fk_Recursos_has_Ferramenta_Recursos1`
    FOREIGN KEY (`Recursos_id_recurso`)
    REFERENCES `mydb`.`Recursos` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recursos_has_Ferramenta_Ferramenta1`
    FOREIGN KEY (`Ferramenta_id_ferramenta`)
    REFERENCES `mydb`.`Ferramenta` (`id_ferramenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `nomeProjeto` VARCHAR(100) NOT NULL,
  `data_inicio_projeto` DATE NOT NULL,
  `data_prevista_termino_projeto` DATE NOT NULL,
  `data_termino_real` DATE NOT NULL,
  `status_projeto` ENUM("Em andamento", "Em Testes", "Não iniciado", "Concluído") NOT NULL,
  `horas_previstas_projeto` INT NOT NULL,
  `Equipe_id_equipe` INT NOT NULL,
  `Equipe_id_equipe1` INT NOT NULL,
  `Recursos_id_gerente` INT NOT NULL,
  PRIMARY KEY (`id_projeto`, `Equipe_id_equipe`),
  INDEX `fk_Projeto_Equipe1_idx` (`Equipe_id_equipe1` ASC) VISIBLE,
  INDEX `fk_Projeto_Recursos1_idx` (`Recursos_id_gerente` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Equipe1`
    FOREIGN KEY (`Equipe_id_equipe1`)
    REFERENCES `mydb`.`Equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Recursos1`
    FOREIGN KEY (`Recursos_id_gerente`)
    REFERENCES `mydb`.`Recursos` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atividade` (
  `id_atividade` INT NOT NULL AUTO_INCREMENT,
  `nome_atividade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_atividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AtividadeProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AtividadeProjeto` (
  `Atividade_id_atividade` INT NOT NULL,
  `Projeto_id_projeto` INT NOT NULL,
  `id_atividade_projeto` INT NOT NULL,
  PRIMARY KEY (`Atividade_id_atividade`, `Projeto_id_projeto`, `id_atividade_projeto`),
  INDEX `fk_Atividade_has_Projeto_Projeto1_idx` (`Projeto_id_projeto` ASC) VISIBLE,
  INDEX `fk_Atividade_has_Projeto_Atividade1_idx` (`Atividade_id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_Atividade_has_Projeto_Atividade1`
    FOREIGN KEY (`Atividade_id_atividade`)
    REFERENCES `mydb`.`Atividade` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atividade_has_Projeto_Projeto1`
    FOREIGN KEY (`Projeto_id_projeto`)
    REFERENCES `mydb`.`Projeto` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarefa` (
  `id_tarefa` INT NOT NULL,
  `descricao_tarefa` TEXT NOT NULL,
  `Atividade_id_atividade` INT NOT NULL,
  PRIMARY KEY (`id_tarefa`),
  INDEX `fk_Tarefa_Atividade1_idx` (`Atividade_id_atividade` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefa_Atividade1`
    FOREIGN KEY (`Atividade_id_atividade`)
    REFERENCES `mydb`.`Atividade` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoricoSalario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HistoricoSalario` (
  `id_historico_salario` INT NOT NULL,
  `data_aumento` DATE NOT NULL,
  `aumento_salario` DECIMAL(10,2) NOT NULL,
  `Recursos_id_recurso` INT NOT NULL,
  PRIMARY KEY (`id_historico_salario`),
  INDEX `fk_HistoricoSalario_Recursos1_idx` (`Recursos_id_recurso` ASC) VISIBLE,
  CONSTRAINT `fk_HistoricoSalario_Recursos1`
    FOREIGN KEY (`Recursos_id_recurso`)
    REFERENCES `mydb`.`Recursos` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
